steps:
  - name: 'maven:3-jdk-11'
    args:
      - 'spring-boot:build-image'
      - '-Pk8s'
      - '-DREPOSITORY_PREFIX=$${REPOSITORY_PREFIX}'
    entrypoint: mvn
  - name: gcr.io/cloud-builders/docker
    args:
      - ./scripts/pushImages.sh
    entrypoint: bash
  - name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - '-f'
      - k8s/init-namespace/
  - name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - '-f'
      - k8s/init-services/
  - name: gcr.io/cloud-builders/gcloud
    args:
      - ./scripts/deployToKubernetes.sh
    entrypoint: bash
  - name: gcr.io/cloud-builders/kubectl
    args:
      - rollout
      - restart
      - deployments
      - '-n'
      - spring-petclinic
options:
  env:
    - CLOUDSDK_COMPUTE_ZONE=europe-central2-b
    - CLOUDSDK_CONTAINER_CLUSTER=petclinic
    - >-
      REPOSITORY_PREFIX=europe-central2-docker.pkg.dev/$PROJECT_ID/petclinic-repo
